import markdown
import datetime
from pathlib import Path
from config import config

def generate_report(search_data: dict) -> str:
    results = search_data.get('results', {})
    analysis = search_data.get('ai_analysis', '')
    query_type = search_data.get('query_type', 'unknown')
    query_value = search_data.get('query_value', 'unknown')
    created_at = search_data.get('created_at', datetime.datetime.utcnow())
    
    if isinstance(created_at, str):
        created_at = datetime.datetime.fromisoformat(created_at)
    
    report_filename = f"report_{search_data.get('id', 'unknown')}_{query_value[:20]}_{created_at.strftime('%Y%m%d_%H%M%S')}.html"
    report_path = config.REPORTS_DIR / report_filename
    
    analysis_html = markdown.markdown(analysis) if analysis else '<p class="has-text-grey">No AI analysis available.</p>'
    
    summary_sections = _build_summary_sections(query_type, results)
    raw_data = _build_raw_data(query_type, results)

    html = f"""<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TracePoint Report - {query_value}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0f; color: #e0e0e0; line-height: 1.6; }}
.container {{ max-width: 1100px; margin: 0 auto; padding: 20px; }}
header {{ background: linear-gradient(135deg, #1a1a2e, #16213e); padding: 40px 0; border-bottom: 3px solid #0f3460; margin-bottom: 30px; }}
header h1 {{ color: #e94560; font-size: 2em; }}
header .meta {{ color: #888; margin-top: 10px; font-size: 0.9em; }}
.section {{ background: #1a1a2e; border-radius: 8px; padding: 25px; margin-bottom: 20px; border: 1px solid #2a2a3e; }}
.section h2 {{ color: #e94560; margin-bottom: 15px; padding-bottom: 8px; border-bottom: 1px solid #2a2a3e; }}
.section h3 {{ color: #0f3460; margin: 15px 0 10px; }}
.badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.8em; font-weight: bold; }}
.badge-success {{ background: #1b5e20; color: #a5d6a7; }}
.badge-warning {{ background: #e65100; color: #ffcc80; }}
.badge-danger {{ background: #b71c1c; color: #ef9a9a; }}
.badge-info {{ background: #0d47a1; color: #90caf9; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 15px; }}
.card {{ background: #12122a; border-radius: 6px; padding: 15px; border: 1px solid #2a2a3e; }}
.card .label {{ color: #888; font-size: 0.85em; }}
.card .value {{ color: #fff; font-size: 1.1em; font-weight: bold; margin-top: 4px; }}
table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
th, td {{ text-align: left; padding: 10px 12px; border-bottom: 1px solid #2a2a3e; }}
th {{ color: #e94560; font-size: 0.85em; text-transform: uppercase; }}
tr:hover {{ background: #1f1f35; }}
a {{ color: #64b5f6; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
pre {{ background: #0a0a0f; padding: 15px; border-radius: 6px; overflow-x: auto; font-size: 0.9em; border: 1px solid #2a2a3e; }}
code {{ font-family: 'Fira Code', monospace; }}
.analysis-content h1, .analysis-content h2, .analysis-content h3 {{ color: #e94560; margin: 15px 0 10px; }}
.analysis-content ul, .analysis-content ol {{ padding-left: 20px; margin: 10px 0; }}
.analysis-content li {{ margin: 5px 0; }}
.analysis-content strong {{ color: #fff; }}
.footer {{ text-align: center; color: #555; padding: 30px 0; font-size: 0.85em; }}
@media print {{
    body {{ background: #fff; color: #333; }}
    .section {{ background: #f5f5f5; border-color: #ddd; }}
    header {{ background: #1a1a2e; }}
    .card {{ background: #e8e8e8; }}
    .card .value {{ color: #000; }}
    th {{ color: #e94560; }}
    tr:hover {{ background: #eee; }}
    .analysis-content strong {{ color: #000; }}
}}
</style>
</head>
<body>
<header>
<div class="container">
<h1>TracePoint Report</h1>
<p style="color:#e94560;font-size:1.2em;margin:5px 0">{query_value}</p>
<p class="meta">
Type: {query_type.upper()} | Generated: {created_at.strftime('%Y-%m-%d %H:%M:%S UTC')} | 
ID: #{search_data.get('id', 'N/A')}
</p>
</div>
</header>

<div class="container">
{summary_sections}

<div class="section">
<h2>AI Analysis</h2>
<div class="analysis-content">{analysis_html}</div>
</div>

<div class="section">
<h2>Raw Data</h2>
<pre><code>{raw_data}</code></pre>
</div>

<div class="footer">
<p>Generated by TracePoint - Intelligence Collection Platform</p>
<p>For authorized use only. Respect privacy and applicable laws.</p>
</div>
</div>
</body>
</html>"""

    config.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(html)

    return str(report_path)

def _build_summary_sections(query_type: str, results: dict) -> str:
    sections = []

    if query_type == 'username':
        profiles = results.get('profiles', [])
        found = [p for p in profiles if p.get('status') == 'found']
        social = results.get('social_analysis', {})
        sections.append(f"""<div class="section">
<h2>Summary</h2>
<div class="grid">
<div class="card"><div class="label">Platforms Checked</div><div class="value">{len(profiles)}</div></div>
<div class="card"><div class="label">Profiles Found</div><div class="value">{len(found)}</div></div>
<div class="card"><div class="label">Profiles Analyzed</div><div class="value">{len(social.get('profiles_analyzed', []))}</div></div>
</div>
</div>""")

        if found:
            sections.append(f"""<div class="section">
<h2>Profiles Found ({len(found)})</h2>
<table>
<tr><th>Platform</th><th>URL</th><th>Status</th></tr>
{''.join(f'<tr><td>{p["platform"]}</td><td><a href="{p["url"]}" target="_blank">{p["url"][:60]}...</a></td><td><span class="badge badge-success">Found</span></td></tr>' for p in found[:30])}
</table>
</div>""")

        if social.get('common_info', {}).get('locations'):
            locs = social['common_info']['locations']
            sections.append(f"""<div class="section">
<h2>Cross-Reference Analysis</h2>
<p><strong>Possible Locations:</strong> {', '.join(locs)}</p>
</div>""")

    elif query_type == 'email':
        gravatar = results.get('gravatar')
        hibp = results.get('hibp', {})
        risk = results.get('risk_score', 0)
        risk_badge = 'badge-success' if risk < 30 else ('badge-warning' if risk < 60 else 'badge-danger')
        sections.append(f"""<div class="section">
<h2>Summary</h2>
<div class="grid">
<div class="card"><div class="label">Risk Score</div><div class="value">{risk}/100 <span class="badge {risk_badge}">{'LOW' if risk < 30 else 'MEDIUM' if risk < 60 else 'HIGH'}</span></div></div>
<div class="card"><div class="label">Data Breaches</div><div class="value">{hibp.get('total_breaches', 0)}</div></div>
<div class="card"><div class="label">Web Mentions</div><div class="value">{len(results.get('web_mentions', []))}</div></div>
</div>
</div>""")

        if gravatar:
            sections.append(f"""<div class="section">
<h2>Gravatar Profile</h2>
<img src="{gravatar.get('avatar', '')}" style="border-radius:50%;width:100px;height:100px;float:right;">
<p><strong>Name:</strong> {gravatar.get('display_name', 'N/A')}</p>
<p><strong>Username:</strong> {gravatar.get('preferred_username', 'N/A')}</p>
<p><strong>Location:</strong> {gravatar.get('current_location', 'N/A')}</p>
<p><strong>Bio:</strong> {gravatar.get('about', 'N/A')}</p>
</div>""")

        if hibp.get('breaches'):
            sections.append(f"""<div class="section">
<h2>Data Breaches</h2>
<table>
<tr><th>Site</th><th>Date</th><th>Data Exposed</th></tr>
{''.join(f'<tr><td>{b.get("name", "?")}</td><td>{b.get("date", "?")}</td><td>{", ".join(b.get("data_classes", []))}</td></tr>' for b in hibp['breaches'])}
</table>
</div>""")

    elif query_type == 'name':
        sections.append(f"""<div class="section">
<h2>Summary</h2>
<div class="grid">
<div class="card"><div class="label">Total Results</div><div class="value">{results.get('total_results', 0)}</div></div>
<div class="card"><div class="label">Social Profiles</div><div class="value">{len(results.get('profiles', []))}</div></div>
<div class="card"><div class="label">Web Mentions</div><div class="value">{len(results.get('web_results', []))}</div></div>
</div>
</div>""")

    elif query_type == 'phone':
        valid = results.get('valid', False)
        sections.append(f"""<div class="section">
<h2>Summary</h2>
<div class="grid">
<div class="card"><div class="label">Valid Number</div><div class="value"><span class="badge {'badge-success' if valid else 'badge-danger'}">{'Yes' if valid else 'No'}</span></div></div>
<div class="card"><div class="label">Country</div><div class="value">{results.get('country', 'N/A')}</div></div>
<div class="card"><div class="label">Carrier</div><div class="value">{results.get('carrier', 'N/A')}</div></div>
</div>
</div>""")

    return '\n'.join(sections)

def _build_raw_data(query_type: str, results: dict) -> str:
    import json
    return json.dumps(results, indent=2, default=str, ensure_ascii=False)[:5000]
